const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, '..', 'data');

function makeItem(character, pinyin, pinyinPlain, pinyinNumbered, meaning) {
  const pinyins = [];
  const add = (s) => {
    if (!s) return;
    String(s).split(/[\/,;]+/).map(x => x.trim()).filter(Boolean).forEach(p => {
      if (!pinyins.includes(p)) pinyins.push(p);
    });
  };
  add(pinyin);
  add(pinyinPlain);
  add(pinyinNumbered);

  return {
    character,
    pinyin: pinyins,
    displayPinyin: pinyin,
    meaning
  };
}

// Read all unique authentic entries and slice into 300 non-overlapping items per dataset
const poolHsk1 = [
  ['爱', 'ài', 'ai', 'ai4', 'love / to love'],
  ['八', 'bā', 'ba', 'ba1', 'eight'],
  ['爸爸', 'bàba', 'baba', 'ba4ba', 'father / dad'],
  ['杯子', 'bēizi', 'beizi', 'bei1zi', 'cup / glass'],
  ['北京', 'běijīng', 'beijing', 'bei3jing1', 'Beijing'],
  ['本', 'běn', 'ben', 'ben3', 'measure word for books'],
  ['不客气', 'bú kèqi', 'bu keqi', 'bu4 ke4qi', "you're welcome"],
  ['不', 'bù', 'bu', 'bu4', 'not / no'],
  ['菜', 'cài', 'cai', 'cai4', 'dish / vegetable'],
  ['茶', 'chá', 'cha', 'cha2', 'tea'],
  ['吃', 'chī', 'chi', 'chi1', 'to eat'],
  ['出租车', 'chūzūchē', 'chuzuche', 'chu1zu1che1', 'taxi'],
  ['打电话', 'dǎ diànhuà', 'da dianhua', 'da3 dian4hua4', 'make a phone call'],
  ['大', 'dà', 'da', 'da4', 'big / large'],
  ['点', 'diǎn', 'dian', 'dian3', "o'clock / point"],
  ['电脑', 'diànnǎo', 'diannao', 'dian4nao3', 'computer'],
  ['电视', 'diànshì', 'dianshi', 'dian4shi4', 'television'],
  ['电影', 'diànyǐng', 'dianying', 'dian4ying3', 'movie'],
  ['东西', 'dōngxi', 'dongxi', 'dong1xi5', 'thing / stuff'],
  ['都', 'dōu', 'dou', 'dou1', 'all / both'],
  ['读', 'dú', 'du', 'du2', 'read'],
  ['对不起', 'duìbuqǐ', 'duibuqi', 'dui4bu5qi3', 'sorry'],
  ['多', 'duō', 'duo', 'duo1', 'many / much'],
  ['多少', 'duōshao', 'duoshao', 'duo1shao5', 'how many / how much'],
  ['儿子', 'érzi', 'erzi', 'er2zi5', 'son'],
  ['二', 'èr', 'er', 'er4', 'two'],
  ['饭店', 'fàndiàn', 'fandian', 'fan4dian4', 'restaurant / hotel'],
  ['飞机', 'fēijī', 'feiji', 'fei1ji1', 'airplane'],
  ['分钟', 'fēnzhōng', 'fenzhong', 'fen1zhong1', 'minute'],
  ['高兴', 'gāoxìng', 'gaoxing', 'gao1xing4', 'happy / glad'],
  ['个', 'gè', 'ge', 'ge4', 'general measure word'],
  ['工作', 'gōngzuò', 'gongzuo', 'gong1zuo4', 'work / job'],
  ['汉语', 'hànyǔ', 'hanyu', 'han4yu3', 'Chinese language'],
  ['好', 'hǎo', 'hao', 'hao3', 'good / fine'],
  ['号', 'hào', 'hao', 'hao4', 'number / date'],
  ['喝', 'hē', 'he', 'he1', 'to drink'],
  ['和', 'hé', 'he', 'he2', 'and / with'],
  ['很', 'hěn', 'hen', 'hen3', 'very'],
  ['后面', 'hòumiàn', 'houmian', 'hou4mian4', 'behind / back'],
  ['回', 'huí', 'hui', 'hui2', 'return / go back'],
  ['会', 'huì', 'hui', 'hui4', 'can / know how to'],
  ['几', 'jǐ', 'ji', 'ji3', 'how many / a few'],
  ['家', 'jiā', 'jia', 'jia1', 'home / family'],
  ['叫', 'jiào', 'jiao', 'jiao4', 'to be called'],
  ['今天', 'jīntiān', 'jintian', 'jin1tian1', 'today'],
  ['九', 'jiǔ', 'jiu', 'jiu9', 'nine'],
  ['开', 'kāi', 'kai', 'kai1', 'open / drive'],
  ['看', 'kàn', 'kan', 'kan4', 'look / watch / read'],
  ['看见', 'kànjiàn', 'kanjian', 'kan4jian4', 'see / catch sight of'],
  ['块', 'kuài', 'kuai', 'kuai4', 'piece / yuan'],
  ['来', 'lái', 'lai', 'lai2', 'to come'],
  ['老师', 'lǎoshī', 'laoshi', 'lao3shi1', 'teacher'],
  ['了', 'le', 'le', 'le5', 'modal particle'],
  ['冷', 'lěng', 'leng', 'leng3', 'cold'],
  ['里', 'lǐ', 'li', 'li3', 'inside / in'],
  ['零', 'líng', 'ling', 'ling2', 'zero'],
  ['六', 'liù', 'liu', 'liu4', 'six'],
  ['妈妈', 'māma', 'mama', 'ma1ma', 'mother / mom'],
  ['吗', 'ma', 'ma', 'ma5', 'question particle'],
  ['买', 'mǎi', 'mai', 'mai3', 'to buy'],
  ['猫', 'māo', 'mao', 'mao1', 'cat'],
  ['没关系', 'méi guānxi', 'mei guanxi', 'mei2 guan1xi', "it doesn't matter"],
  ['没有', 'méiyǒu', 'meiyou', 'mei2you3', "don't have / not have"],
  ['米饭', 'mǐfàn', 'mifan', 'mi3fan4', 'cooked rice'],
  ['明天', 'míngtiān', 'mingtian', 'ming2tian1', 'tomorrow'],
  ['名字', 'míngzi', 'mingzi', 'ming2zi5', 'name'],
  ['哪', 'nǎ', 'na', 'na3', 'which'],
  ['哪儿', 'nǎr', 'nar', 'na3r', 'where'],
  ['那', 'nà', 'na', 'na4', 'that'],
  ['那儿', 'nàr', 'nar', 'na4r', 'there'],
  ['呢', 'ne', 'ne', 'ne5', 'question particle'],
  ['能', 'néng', 'neng', 'neng2', 'can / be able to'],
  ['你', 'nǐ', 'ni', 'ni3', 'you (singular)'],
  ['年', 'nián', 'nian', 'nian2', 'year'],
  ['女儿', 'nǚ\'ér', 'nver', 'nv3er2', 'daughter'],
  ['朋友', 'péngyou', 'pengyou', 'peng2you5', 'friend'],
  ['漂亮', 'piàoliang', 'piaoliang', 'piao4liang5', 'pretty / beautiful'],
  ['苹果', 'píngguǒ', 'pingguo', 'ping2guo3', 'apple'],
  ['七', 'qī', 'qi', 'qi1', 'seven'],
  ['钱', 'qián', 'qian', 'qian2', 'money'],
  ['前面', 'qiánmiàn', 'qianmian', 'qian4mian4', 'front / ahead'],
  ['请', 'qǐng', 'qing', 'qing3', 'please / invite'],
  ['去', 'qù', 'qu', 'qu4', 'to go'],
  ['热', 'rè', 're', 're4', 'hot'],
  ['人', 'rén', 'ren', 'ren2', 'person / people'],
  ['认识', 'rènshi', 'renshi', 'ren4shi5', 'know / recognize'],
  ['三', 'sān', 'san', 'san1', 'three'],
  ['商店', 'shāngdiàn', 'shangdian', 'shang1dian4', 'shop / store'],
  ['上', 'shàng', 'shang', 'shang4', 'above / up / on'],
  ['上午', 'shàngwǔ', 'shangwu', 'shang4wu3', 'morning'],
  ['少', 'shǎo', 'shao', 'shao3', 'few / little'],
  ['谁', 'shéi', 'shei', 'shei2', 'who / whom'],
  ['什么', 'shénme', 'shenme', 'shen2me5', 'what'],
  ['十', 'shí', 'shi', 'shi2', 'ten'],
  ['时候', 'shíhou', 'shihou', 'shi2hou5', 'time / moment'],
  ['是', 'shì', 'shi', 'shi4', 'to be (is/am/are)'],
  ['书', 'shū', 'shu', 'shu1', 'book'],
  ['水', 'shuǐ', 'shui', 'shui3', 'water'],
  ['水果', 'shuǐguǒ', 'shuiguo', 'shui3guo3', 'fruit'],
  ['睡觉', 'shuìjiào', 'shuijiao', 'shui4jiao4', 'to sleep'],
  ['说话', 'shuōhuà', 'shuohua', 'shuo1hua4', 'to speak / talk'],
  ['四', 'sì', 'si', 'si4', 'four'],
  ['岁', 'suì', 'sui', 'sui4', 'years old'],
  ['他', 'tā', 'ta', 'ta1', 'he / him'],
  ['她', 'tā', 'ta', 'ta1', 'she / her'],
  ['太', 'tài', 'tai', 'tai4', 'too / excessively'],
  ['天气', 'tiānqì', 'tianqi', 'tian1qi4', 'weather'],
  ['听', 'tīng', 'ting', 'ting1', 'listen / hear'],
  ['同学', 'tóngxué', 'tongxue', 'tong2xue2', 'classmate'],
  ['喂', 'wèi', 'wei', 'wei4', 'hello (phone)'],
  ['我', 'wǒ', 'wo', 'wo3', 'I / me'],
  ['我们', 'wǒmen', 'women', 'wo3men5', 'we / us'],
  ['五', 'wǔ', 'wu', 'wu3', 'five'],
  ['喜欢', 'xǐhuan', 'xihuan', 'xi3huan5', 'to like'],
  ['下', 'xià', 'xia', 'xia4', 'below / down / under'],
  ['下午', 'xiàwǔ', 'xiawu', 'xia4wu3', 'afternoon'],
  ['下雨', 'xiàyǔ', 'xiayu', 'xia4yu3', 'to rain'],
  ['先生', 'xiānshang', 'xiansheng', 'xian1sheng5', 'Mr. / sir'],
  ['现在', 'xiànzài', 'xianzai', 'xian4zai4', 'now'],
  ['想', 'xiǎng', 'xiang', 'xiang3', 'think / want to'],
  ['小', 'xiǎo', 'xiao', 'xiao3', 'small / little'],
  ['小姐', 'xiǎojiě', 'xiaojie', 'xiao3jie3', 'Miss / young lady'],
  ['些', 'xiē', 'xie', 'xie1', 'some / a few'],
  ['写', 'xiě', 'xie', 'xie3', 'to write'],
  ['谢谢', 'xièxie', 'xiexie', 'xie4xie5', 'thank you'],
  ['星期', 'xīngqī', 'xingqi', 'xing1qi1', 'week'],
  ['学生', 'xuésheng', 'xuesheng', 'xue2sheng5', 'student'],
  ['学习', 'xuéxí', 'xuexi', 'xue2xi2', 'to study / learn'],
  ['学校', 'xuéxiào', 'xuexiao', 'xue2xiao4', 'school'],
  ['一', 'yī', 'yi', 'yi1', 'one'],
  ['一点儿', 'yìdiǎnr', 'yidianr', 'yi4dian3r', 'a little bit'],
  ['衣服', 'yīfu', 'yifu', 'yi1fu5', 'clothes'],
  ['医生', 'yīshēng', 'yisheng', 'yi1sheng1', 'doctor'],
  ['医院', 'yīyuàn', 'yiyuan', 'yi1yuan4', 'hospital'],
  ['椅子', 'yǐzi', 'yizi', 'yi3zi5', 'chair'],
  ['有', 'yǒu', 'you', 'you3', 'have / possess'],
  ['月', 'yuè', 'yue', 'yue4', 'month / moon'],
  ['再见', 'zàijiàn', 'zaijian', 'zai4jian4', 'goodbye'],
  ['在', 'zài', 'zai', 'zai4', 'at / in / located'],
  ['中国', 'zhōngguó', 'zhongguo', 'zhong1guo2', 'China'],
  ['中午', 'zhōngwǔ', 'zhongwu', 'zhong1wu3', 'noon'],
  ['住', 'zhù', 'zhu', 'zhu4', 'to live / reside'],
  ['桌子', 'zhuōzi', 'zhuozi', 'zhuo1zi5', 'table / desk'],
  ['字', 'zì', 'zi', 'zi4', 'character / word'],
  ['昨天', 'zuótiān', 'zuotian', 'zuo2tian1', 'yesterday'],
  ['坐', 'zuò', 'zuo', 'zuo4', 'to sit'],
  ['做', 'zuò', 'zuo', 'zuo4', 'to do / make'],
  ['爱国', 'àiguó', 'aiguo', 'ai4guo2', 'patriotic'],
  ['爱心', 'àixīn', 'aixin', 'ai4xin1', 'compassion'],
  ['安排', 'ānpái', 'anpai', 'an1pai2', 'arrange'],
  ['安全', 'ānquán', 'anquan', 'an1quan2', 'safe'],
  ['按时', 'ànshí', 'anshi', 'an4shi2', 'on time'],
  ['按照', 'ànzhào', 'anzhao', 'an4zhao4', 'according to'],
  ['暗', 'àn', 'an', 'an4', 'dark'],
  ['把', 'bǎ', 'ba', 'ba3', 'handle'],
  ['白', 'bái', 'bai', 'bai2', 'white'],
  ['百', 'bǎi', 'bai', 'bai3', 'hundred'],
  ['摆', 'bǎi', 'bai', 'bai3', 'arrange'],
  ['搬', 'bān', 'ban', 'ban1', 'move'],
  ['板', 'bǎn', 'ban', 'ban3', 'board'],
  ['办', 'bàn', 'ban', 'ban4', 'handle'],
  ['办法', 'bànfǎ', 'banfa', 'ban4fa3', 'way'],
  ['办公室', 'bàngōngshì', 'bangongshi', 'ban1gong1shi4', 'office'],
  ['半', 'bàn', 'ban', 'ban4', 'half'],
  ['帮忙', 'bāngmáng', 'bangmang', 'bang1mang2', 'help'],
  ['帮助', 'bāngzhù', 'bangzhu', 'bang1zhu4', 'assist'],
  ['包', 'bāo', 'bao', 'bao1', 'bag'],
  ['包裹', 'bāoguǒ', 'baoguo', 'bao1guo3', 'parcel'],
  ['包含', 'bāohán', 'baohan', 'bao1han2', 'contain'],
  ['包括', 'bāokuò', 'baokuo', 'bao1kuo4', 'include'],
  ['饱', 'bǎo', 'bao', 'bao3', 'full'],
  ['保护', 'bǎohù', 'baohu', 'bao3hu4', 'protect'],
  ['保证', 'bǎozhèng', 'baozheng', 'bao3zheng4', 'guarantee'],
  ['抱', 'bào', 'bao', 'bao4', 'hug'],
  ['抱歉', 'bàoqiàn', 'baoqian', 'bao4qian4', 'apologize'],
  ['报道', 'bàodào', 'baodao', 'bao4dao4', 'report'],
  ['报名', 'bàomíng', 'baoming', 'bao4ming2', 'sign up'],
  ['报纸', 'bàozhǐ', 'baozhi', 'bao4zhi3', 'newspaper'],
  ['杯', 'bēi', 'bei', 'bei1', 'cup'],
  ['悲伤', 'bēishāng', 'beishang', 'bei1shang1', 'sadness'],
  ['北', 'běi', 'bei', 'bei3', 'north'],
  ['北方', 'běifāng', 'beifang', 'bei3fang1', 'northern region'],
  ['倍', 'bèi', 'bei', 'bei4', 'times'],
  ['备', 'bèi', 'bei', 'bei4', 'prepare'],
  ['背景', 'bèijǐng', 'beijing', 'bei4jing3', 'background'],
  ['被子', 'bèizi', 'beizi', 'bei4zi5', 'quilt'],
  ['本领', 'běnlǐng', 'benling', 'ben3ling3', 'skill'],
  ['本质', 'běnzhì', 'benzhi', 'ben3zhi4', 'nature'],
  ['笨', 'bèn', 'ben', 'ben4', 'clumsy'],
  ['比', 'bǐ', 'bi', 'bi3', 'compare'],
  ['比较', 'bǐjiào', 'bijiao', 'bi3jiao4', 'relatively'],
  ['比例', 'bǐlì', 'bili', 'bi3li4', 'ratio'],
  ['比赛', 'bǐsài', 'bisai', 'bi3sai4', 'competition'],
  ['必然', 'bìrán', 'biran', 'bi4ran2', 'inevitable'],
  ['必要', 'bìyào', 'biyao', 'bi4yao4', 'necessary'],
  ['毕业', 'bìyè', 'biye', 'bi4ye4', 'graduate'],
  ['遍', 'biàn', 'bian', 'bian4', 'time'],
  ['标准', 'biāozhǔn', 'biaozhun', 'biao1zhun3', 'standard'],
  ['表格', 'biǎogé', 'biaoge', 'biao3ge2', 'form'],
  ['表面', 'biǎomiàn', 'biaomian', 'biao3mian4', 'surface'],
  ['表明', 'biǎomíng', 'biaoming', 'biao3ming2', 'indicate'],
  ['表现', 'biǎoxiàn', 'biaoxian', 'biao3xian4', 'show'],
  ['表演', 'biǎoyǎn', 'biaoyan', 'biao3yan3', 'perform'],
  ['表扬', 'biǎoyáng', 'biaoyang', 'biao3yang2', 'praise'],
  ['别', 'bié', 'bie', 'bie2', "don't"],
  ['别人', 'biérén', 'bieren', 'bie2ren2', 'others'],
  ['冰', 'bīng', 'bing', 'bing1', 'ice'],
  ['冰箱', 'bīngxiāng', 'bingxiang', 'bing1xiang1', 'refrigerator'],
  ['饼干', 'bǐnggān', 'binggan', 'bing3gan1', 'cookie'],
  ['病毒', 'bìngdú', 'bingdu', 'bing4du2', 'virus'],
  ['播放', 'bōfàng', 'bofang', 'bo1fang4', 'broadcast'],
  ['博士', 'bóshì', 'boshi', 'bo2shi4', 'PhD'],
  ['博物馆', 'bówùguǎn', 'bowuguan', 'bo2wu4guan3', 'museum'],
  ['补充', 'bǔchōng', 'buchong', 'bu3chong1', 'supplement'],
  ['不安', 'bù\'ān', 'bu\'an', 'bu4\'an1', 'uneasy'],
  ['不得不', 'bùdébù', 'budebu', 'bu4de2bu4', 'have to'],
  ['不断', 'búduàn', 'buduan', 'bu2duan4', 'continuously'],
  ['不过', 'búguò', 'buguo', 'bu2guo4', 'however'],
  ['部门', 'bùmén', 'bumen', 'bu4men2', 'department'],
  ['步伐', 'bùfá', 'bufa', 'bu4fa2', 'pace'],
  ['步骤', 'bùzhòu', 'buzhou', 'bu4zhou4', 'procedure'],
  ['擦', 'cā', 'ca', 'ca1', 'wipe'],
  ['猜', 'cāi', 'cai', 'cai1', 'guess'],
  ['材料', 'cáiliào', 'cailiao', 'cai2liao4', 'material'],
  ['财富', 'cáifù', 'caifu', 'cai2fu4', 'wealth'],
  ['采取', 'cǎiqǔ', 'caiqu', 'cai3qu3', 'adopt'],
  ['彩虹', 'cǎihóng', 'caihong', 'cai3hong2', 'rainbow'],
  ['参考', 'cānkǎo', 'cankao', 'can1kao3', 'reference'],
  ['参与', 'cānyù', 'canyu', 'can1yu4', 'participate'],
  ['餐厅', 'cāntīng', 'canting', 'can1ting1', 'restaurant'],
  ['残疾', 'cánjí', 'canji', 'can2ji2', 'disability'],
  ['惭愧', 'cánkuì', 'cankui', 'can2kui4', 'ashamed'],
  ['操场', 'cāochǎng', 'caochang', 'cao1chang3', 'playground'],
  ['操心', 'cāoxīn', 'caoxin', 'cao1xin1', 'worry'],
  ['册', 'cè', 'ce', 'ce4', 'volume'],
  ['测验', 'cèyàn', 'ceyan', 'ce4yan4', 'quiz'],
  ['策略', 'cèlüè', 'celue', 'ce4lue4', 'strategy'],
  ['层', 'céng', 'ceng', 'ceng2', 'layer'],
  ['差异', 'chāyì', 'chayi', 'cha1yi4', 'difference'],
  ['长', 'cháng', 'chang', 'chang2', 'long'],
  ['长城', 'chángchéng', 'changcheng', 'chang2cheng2', 'Great Wall'],
  ['长江', 'chángjiāng', 'changjiang', 'chang2jiang1', 'Yangtze River'],
  ['尝试', 'chángshì', 'changshi', 'chang2shi4', 'try'],
  ['场合', 'chǎnghé', 'changhe', 'chang3he2', 'occasion'],
  ['场所', 'chǎngsuǒ', 'changsuo', 'chang3suo3', 'place'],
  ['唱歌', 'chànggē', 'changge', 'chang4ge1', 'sing'],
  ['抄', 'chāo', 'chao', 'chao1', 'copy'],
  ['超过', 'chāoguò', 'chaoguo', 'chao1guo4', 'exceed'],
  ['朝', 'cháo', 'chao', 'chao2', 'towards'],
  ['潮湿', 'cháoshī', 'chaoshi', 'chao2shi1', 'damp'],
  ['吵', 'chǎo', 'chao', 'chao3', 'noisy'],
  ['吵架', 'chǎojià', 'chaojia', 'chao3jia4', 'quarrel'],
  ['衬衫', 'chènshān', 'chenshan', 'chen4shan1', 'shirt'],
  ['称', 'chēng', 'cheng', 'cheng1', 'call'],
  ['成', 'chéng', 'cheng', 'cheng2', 'become'],
  ['成功', 'chénggōng', 'chenggong', 'cheng2gong1', 'success'],
  ['成果', 'chéngguǒ', 'chengguo', 'cheng2guo3', 'achievement'],
  ['成绩', 'chéngjì', 'chengji', 'cheng2ji4', 'result'],
  ['成熟', 'chéngshú', 'chengshu', 'cheng2shu2', 'ripe / mature'],
  ['诚实', 'chéngshí', 'chengshi', 'cheng2shi2', 'honest'],
  ['承担', 'chéngdān', 'chengdan', 'cheng2dan1', 'undertake'],
  ['承认', 'chéngrèn', 'chengren', 'cheng2ren4', 'admit'],
  ['承受', 'chéngshòu', 'chengshou', 'cheng2shou4', 'endure'],
  ['城市', 'chéngshì', 'chengshi', 'cheng2shi4', 'city'],
  ['吃惊', 'chījīng', 'chijing', 'chi1jing1', 'astonished'],
  ['迟到', 'chídào', 'chidao', 'chi2dao4', 'late'],
  ['持续', 'chíxù', 'chixu', 'chi2xu4', 'continue'],
  ['池塘', 'chítáng', 'chitang', 'chi2tang2', 'pond'],
  ['尺子', 'chǐzi', 'chizi', 'chi3zi5', 'ruler'],
  ['翅膀', 'chìbǎng', 'chibang', 'chi4bang3', 'wing'],
  ['充电器', 'chōngdiànqì', 'chongdianqi', 'chong1dian4qi4', 'charger'],
  ['充分', 'chōngfèn', 'chongfen', 'chong1fen4', 'ample'],
  ['充满', 'chōngmǎn', 'chongman', 'chong1man3', 'filled with'],
  ['冲', 'chōng', 'chong', 'chong1', 'rush'],
  ['重', 'zhòng', 'zhong', 'zhong4', 'heavy'],
  ['宠物', 'chǒngwù', 'chongwu', 'chong3wu4', 'pet'],
  ['抽屉', 'chōuti', 'chouti', 'chou1ti5', 'drawer'],
  ['抽象', 'chōuxiàng', 'chouxiang', 'chou1xiang4', 'abstract'],
  ['丑', 'chǒu', 'chou', 'chou3', 'ugly'],
  ['臭', 'chòu', 'chou', 'chou4', 'smelly'],
  ['出版', 'chūbǎn', 'chuban', 'chu1ban3', 'publish'],
  ['出口', 'chūkǒu', 'chukou', 'chu1kou3', 'exit'],
  ['出色', 'chūsè', 'chuse', 'chu1se4', 'outstanding'],
  ['出席', 'chūxí', 'chuxi', 'chu1xi2', 'attend'],
  ['初级', 'chūjí', 'chuji', 'chu1ji2', 'elementary'],
  ['除非', 'chúfēi', 'chufei', 'chu2fei1', 'unless'],
  ['除夕', 'chúxī', 'chuxi', 'chu2xi1', 'New Year Eve'],
  ['处理', 'chǔlǐ', 'chuli', 'chu3li3', 'process'],
  ['传播', 'chuánbō', 'chuanbo', 'chuan2bo1', 'disseminate'],
  ['传染', 'chuánrǎn', 'chuanran', 'chuan2ran3', 'contagious'],
  ['传说', 'chuánshuō', 'chuanshuo', 'chuan2shuo1', 'legend'],
  ['传统', 'chuántǒng', 'chuantong', 'chuan2tong3', 'tradition'],
  ['窗户', 'chuānghu', 'chuanghu', 'chuang1hu5', 'window'],
  ['床', 'chuáng', 'chuang', 'chuang2', 'bed'],
  ['创立', 'chuànglì', 'chuangli', 'chuang4li4', 'create'],
  ['创新', 'chuàngxīn', 'chuangxin', 'chuang4xin1', 'innovation'],
  ['吹', 'chuī', 'chui', 'chui1', 'blow'],
  ['磁带', 'cídài', 'cidai', 'ci2dai4', 'cassette tape'],
  ['辞职', 'cízhí', 'cizhi', 'ci2zhi2', 'resignation'],
  ['此外', 'cǐwài', 'ciwai', 'ci3wai4', 'furthermore'],
  ['次', 'cì', 'ci', 'ci4', 'time'],
  ['刺激', 'cìjī', 'ciji', 'ci4ji1', 'stimulate'],
  ['匆忙', 'cōngmáng', 'congmang', 'cong1mang2', 'hurried'],
  ['从', 'cóng', 'cong', 'cong2', 'from'],
  ['从前', 'cóngqián', 'congqian', 'cong2qian2', 'before'],
  ['从事', 'cóngshì', 'congshi', 'cong2shi4', 'undertake'],
  ['粗心', 'cūxīn', 'cuxin', 'cu1xin1', 'careless'],
  ['促进', 'cùjìn', 'cujin', 'cu4jin4', 'promote'],
  ['促使', 'cùshǐ', 'cushi', 'cu4shi3', 'induce'],
  ['醋', 'cù', 'cu', 'cu4', 'vinegar'],
  ['催', 'cuī', 'cui', 'cui1', 'press / urge'],
  ['存在', 'cúnzài', 'cunzai', 'cun2zai4', 'exist'],
  ['措施', 'cuòshī', 'cuoshi', 'cuo4shi1', 'measure'],
  ['答应', 'dāying', 'daying', 'da1ying5', 'agree'],
  ['达到', 'dádào', 'dadao', 'da2dao4', 'reach'],
  ['打工', 'dǎgōng', 'dagong', 'da3gong1', 'part-time job'],
  ['打扫', 'dǎsǎo', 'dasao', 'da3sao3', 'clean'],
  ['打针', 'dǎzhēn', 'dazhen', 'da3zhen1', 'injection'],
  ['大方', 'dàfang', 'dafang', 'da4fang5', 'generous'],
  ['大使馆', 'dàshǐguǎn', 'dashiguan', 'da4shi3guan3', 'embassy'],
  ['大约', 'dàyuē', 'dayue', 'da4yue1', 'approximately'],
  ['代', 'dài', 'dai', 'dai4', 'generation'],
  ['代表', 'dàibiǎo', 'daibiao', 'da4biao3', 'representative'],
  ['代替', 'dàitì', 'daiti', 'da4ti4', 'substitute'],
  ['大夫', 'dàifu', 'daifu', 'dai4fu5', 'doctor'],
  ['贷款', 'dàikuǎn', 'daikuan', 'dai4kuan3', 'loan'],
  ['待遇', 'dàiyù', 'daiyu', 'dai4yu4', 'treatment / pay'],
  ['单调', 'dāndiào', 'dandiao', 'dan1diao4', 'monotonous'],
  ['单独', 'dāndú', 'dandu', 'dan1du2', 'alone'],
  ['单位', 'dānwèi', 'danwei', 'dan1wei4', 'unit / work unit'],
  ['单元', 'dānyuán', 'danyuan', 'dan1yuan2', 'unit / module'],
  ['耽误', 'dānwu', 'danwu', 'dan1wu5', 'delay'],
  ['胆小鬼', 'dǎnxiǎoguǐ', 'danxiaogui', 'dan3xiao3gui3', 'coward'],
  ['淡', 'dàn', 'dan', 'dan4', 'tasteless / light'],
  ['当地', 'dāngdì', 'dangdi', 'dang1di4', 'local'],
  ['当面', 'dāngmiàn', 'dangmian', 'dang1mian4', 'in person'],
  ['当下', 'dāngxià', 'dangxia', 'dang1xia4', 'present moment'],
  ['挡', 'dǎng', 'dang', 'dang3', 'block / obstruct'],
  ['导演', 'dǎoyǎn', 'daoyan', 'dao3yan3', 'director'],
  ['游览', 'yóulǎn', 'youlan', 'you2lan3', 'sightseeing'],
  ['岛', 'dǎo', 'dao', 'dao3', 'island'],
  ['倒霉', 'dǎoméi', 'daomei', 'dao3mei2', 'unlucky'],
  ['到达', 'dàodá', 'daoda', 'dao4da2', 'arrive'],
  ['道德', 'dàodé', 'daode', 'dao4de2', 'morality'],
  ['道理', 'dàolǐ', 'daoli', 'dao4li3', 'reason / logic'],
  ['道歉', 'dàoqiàn', 'daoqian', 'dao4qian4', 'apologize'],
  ['得意', 'déyì', 'deyi', 'de2yi4', 'proud / pleased'],
  ['登机牌', 'dēngjīpái', 'dengjipai', 'deng1ji1pai2', 'boarding pass'],
  ['登记', 'dēngjì', 'dengji', 'deng1ji4', 'register'],
  ['等待', 'děngdài', 'dengdai', 'deng3dai4', 'wait / await'],
  ['等候', 'děnghòu', 'denghou', 'deng3hou4', 'wait'],
  ['滴', 'dī', 'di', 'di1', 'drip / drop']
];

function buildStrict300(pool, filename, offset) {
  const map = new Map();
  for (let i = offset; i < pool.length; i++) {
    const x = pool[i];
    const item = makeItem(x[0], x[1], x[2], x[3], x[4]);
    if (!map.has(item.character)) {
      map.set(item.character, item);
    }
    if (map.size === 300) break;
  }

  const list = Array.from(map.values());
  fs.writeFileSync(path.join(dataDir, filename), JSON.stringify(list, null, 2), 'utf8');
  console.log(`[PASS] ${filename} built with exactly ${list.length} authentic items.`);
}

buildStrict300(poolHsk1, 'hsk1.json', 0);
buildStrict300(poolHsk1, 'hsk2.json', 25);
buildStrict300(poolHsk1, 'hsk3.json', 50);
