/**
 * Script: diff_hsk_sources.js
 * Compares MandarinBean HSK 1, 2, 3 PDF wordlists (with 4 ground-truth corrections)
 * against existing data/hsk1.json, data/hsk2.json, data/hsk3.json.
 */

const fs = require('fs');
const path = require('path');

// 1. MandarinBean Raw Datasets (150 + 150 + 300) with 4 explicit corrections applied
const MANDARIN_BEAN_HSK1 = [
  { no: 1, char: "我", pinyin: "wǒ", meaning: "I, me" },
  { no: 2, char: "我们", pinyin: "wǒmen", meaning: "we, us (pl.)" },
  { no: 3, char: "你", pinyin: "nǐ", meaning: "you" },
  { no: 4, char: "他", pinyin: "tā", meaning: "he, him" },
  { no: 5, char: "她", pinyin: "tā", meaning: "she, her" },
  { no: 6, char: "这（这儿）", pinyin: "zhè (zhèr)", meaning: "this (here)" },
  { no: 7, char: "那（那儿）", pinyin: "nà (nàr)", meaning: "that (there)" },
  { no: 8, char: "哪", pinyin: "nǎ", meaning: "which" },
  { no: 9, char: "哪儿", pinyin: "nǎr", meaning: "where" },
  { no: 10, char: "谁", pinyin: "shéi", meaning: "who" },
  { no: 11, char: "什么", pinyin: "shénme", meaning: "what, why" },
  { no: 12, char: "多少", pinyin: "duōshǎo", meaning: "how many, how much" },
  { no: 13, char: "几", pinyin: "jǐ", meaning: "a few, how many" },
  { no: 14, char: "怎么", pinyin: "zěnme", meaning: "how" },
  { no: 15, char: "怎么样", pinyin: "zěnmeyàng", meaning: "how about" },
  { no: 16, char: "一", pinyin: "yī", meaning: "one" },
  { no: 17, char: "二", pinyin: "èr", meaning: "two" },
  { no: 18, char: "三", pinyin: "sān", meaning: "three" },
  { no: 19, char: "四", pinyin: "sì", meaning: "four" },
  { no: 20, char: "五", pinyin: "wǔ", meaning: "five" },
  { no: 21, char: "六", pinyin: "liù", meaning: "six" },
  { no: 22, char: "七", pinyin: "qī", meaning: "seven" },
  { no: 23, char: "八", pinyin: "bā", meaning: "eight" },
  { no: 24, char: "九", pinyin: "jiǔ", meaning: "nine" },
  { no: 25, char: "十", pinyin: "shí", meaning: "ten" },
  { no: 26, char: "个", pinyin: "gè", meaning: "(for normal objects)" },
  { no: 27, char: "岁", pinyin: "suì", meaning: "(for age)" },
  { no: 28, char: "本", pinyin: "běn", meaning: "(for books)" },
  { no: 29, char: "些", pinyin: "xiē", meaning: "some" },
  { no: 30, char: "块", pinyin: "kuài", meaning: "piece, chunk" },
  { no: 31, char: "不", pinyin: "bù", meaning: "no" },
  { no: 32, char: "没", pinyin: "méi", meaning: "no" },
  { no: 33, char: "很", pinyin: "hěn", meaning: "quite, very" },
  { no: 34, char: "太", pinyin: "tài", meaning: "too" },
  { no: 35, char: "都", pinyin: "dōu", meaning: "all" },
  { no: 36, char: "一点儿", pinyin: "yīdiǎnr", meaning: "a little bit" },
  { no: 37, char: "和", pinyin: "hé", meaning: "and" },
  { no: 38, char: "在", pinyin: "zài", meaning: "in, at" },
  { no: 39, char: "的", pinyin: "de", meaning: "" },
  { no: 40, char: "了", pinyin: "le", meaning: "" },
  { no: 41, char: "吗", pinyin: "ma", meaning: "" },
  { no: 42, char: "呢", pinyin: "ne", meaning: "" },
  { no: 43, char: "喂", pinyin: "wèi", meaning: "hello" },
  { no: 44, char: "家", pinyin: "jiā", meaning: "home" },
  { no: 45, char: "学校", pinyin: "xuéxiào", meaning: "school" },
  { no: 46, char: "饭店", pinyin: "fàndiàn", meaning: "restaurant" },
  { no: 47, char: "商店", pinyin: "shāngdiàn", meaning: "store" },
  { no: 48, char: "医院", pinyin: "yīyuàn", meaning: "hospital" },
  { no: 49, char: "中国", pinyin: "Zhōngguó", meaning: "China" },
  { no: 50, char: "北京", pinyin: "Běijīng", meaning: "Beijing" },
  { no: 51, char: "上", pinyin: "shàng", meaning: "up" },
  { no: 52, char: "下", pinyin: "xià", meaning: "down" },
  { no: 53, char: "前面", pinyin: "qiánmiàn", meaning: "front" },
  { no: 54, char: "后面", pinyin: "hòumiàn", meaning: "behind" },
  // CORRECTION 1: 里 (HSK1 #55) pinyin is "lǐ", not "lǐmiàn"
  { no: 55, char: "里", pinyin: "lǐ", meaning: "inside" },
  { no: 56, char: "今天", pinyin: "jīntiān", meaning: "today" },
  { no: 57, char: "明天", pinyin: "míngtiān", meaning: "tomorrow" },
  { no: 58, char: "昨天", pinyin: "zuótiān", meaning: "yesterday" },
  { no: 59, char: "上午", pinyin: "shàngwǔ", meaning: "morning" },
  { no: 60, char: "中午", pinyin: "zhōngwǔ", meaning: "noon" },
  { no: 61, char: "下午", pinyin: "xiàwǔ", meaning: "afternoon" },
  { no: 62, char: "年", pinyin: "nián", meaning: "year" },
  { no: 63, char: "月", pinyin: "yuè", meaning: "month" },
  { no: 64, char: "号", pinyin: "hào", meaning: "number/date" },
  { no: 65, char: "星期", pinyin: "xīngqī", meaning: "week" },
  { no: 66, char: "点", pinyin: "diǎn", meaning: "o'clock" },
  { no: 67, char: "分钟", pinyin: "fēnzhōng", meaning: "minute" },
  { no: 68, char: "现在", pinyin: "xiànzài", meaning: "now" },
  { no: 69, char: "时候", pinyin: "shíhou", meaning: "time" },
  { no: 70, char: "爸爸", pinyin: "bàba", meaning: "father" },
  { no: 71, char: "妈妈", pinyin: "māma", meaning: "mother" },
  { no: 72, char: "儿子", pinyin: "érzi", meaning: "son" },
  { no: 73, char: "女儿", pinyin: "nǚér", meaning: "daughter" },
  { no: 74, char: "老师", pinyin: "lǎoshī", meaning: "teacher" },
  { no: 75, char: "学生", pinyin: "xuéshēng", meaning: "student" },
  { no: 76, char: "同学", pinyin: "tóngxué", meaning: "classmate" },
  { no: 77, char: "朋友", pinyin: "péngyǒu", meaning: "friend" },
  { no: 78, char: "医生", pinyin: "yīshēng", meaning: "doctor" },
  { no: 79, char: "先生", pinyin: "xiānsheng", meaning: "sir" },
  { no: 80, char: "小姐", pinyin: "xiǎojiě", meaning: "Miss" },
  { no: 81, char: "衣服", pinyin: "yīfu", meaning: "cloth" },
  { no: 82, char: "水", pinyin: "shuǐ", meaning: "water" },
  { no: 83, char: "菜", pinyin: "cài", meaning: "dish" },
  { no: 84, char: "米饭", pinyin: "mǐfàn", meaning: "rice" },
  { no: 85, char: "水果", pinyin: "shuǐguǒ", meaning: "fruit" },
  { no: 86, char: "苹果", pinyin: "píngguǒ", meaning: "apple" },
  { no: 87, char: "茶", pinyin: "chá", meaning: "tea" },
  { no: 88, char: "杯子", pinyin: "bēizi", meaning: "cup" },
  { no: 89, char: "钱", pinyin: "qián", meaning: "money" },
  { no: 90, char: "飞机", pinyin: "fēijī", meaning: "airplane" },
  { no: 91, char: "出租车", pinyin: "chūzūchē", meaning: "taxi" },
  { no: 92, char: "电视", pinyin: "diànshì", meaning: "television" },
  { no: 93, char: "电脑", pinyin: "diànnǎo", meaning: "computer" },
  { no: 94, char: "电影", pinyin: "diànyǐng", meaning: "movie" },
  { no: 95, char: "天气", pinyin: "tiānqì", meaning: "weather" },
  { no: 96, char: "猫", pinyin: "māo", meaning: "cat" },
  { no: 97, char: "狗", pinyin: "gǒu", meaning: "dog" },
  { no: 98, char: "东西", pinyin: "dōngxi", meaning: "thing" },
  { no: 99, char: "人", pinyin: "rén", meaning: "person" },
  { no: 100, char: "名字", pinyin: "míngzi", meaning: "name" },
  { no: 101, char: "书", pinyin: "shū", meaning: "book" },
  { no: 102, char: "汉语", pinyin: "hànyǔ", meaning: "mandarin Chinese" },
  { no: 103, char: "字", pinyin: "zì", meaning: "character" },
  { no: 104, char: "桌子", pinyin: "zhuōzi", meaning: "desk" },
  { no: 105, char: "椅子", pinyin: "yǐzi", meaning: "chair" },
  { no: 106, char: "谢谢", pinyin: "xièxie", meaning: "thank" },
  { no: 107, char: "不客气", pinyin: "búkèqì", meaning: "you are welcome" },
  { no: 108, char: "再见", pinyin: "zàijiàn", meaning: "good-bye" },
  { no: 109, char: "请", pinyin: "qǐng", meaning: "please" },
  { no: 110, char: "对不起", pinyin: "duìbùqǐ", meaning: "sorry" },
  { no: 111, char: "没关系", pinyin: "méiguānxì", meaning: "It doesn't matter" },
  { no: 112, char: "是", pinyin: "shì", meaning: "be (am, is, are)" },
  { no: 113, char: "有", pinyin: "yǒu", meaning: "have" },
  { no: 114, char: "看", pinyin: "kàn", meaning: "look" },
  { no: 115, char: "听", pinyin: "tīng", meaning: "listen" },
  { no: 116, char: "说", pinyin: "shuō", meaning: "speak" },
  { no: 117, char: "读", pinyin: "dú", meaning: "read" },
  { no: 118, char: "写", pinyin: "xiě", meaning: "write" },
  { no: 119, char: "看见", pinyin: "kànjiàn", meaning: "see" },
  { no: 120, char: "叫", pinyin: "jiào", meaning: "call" },
  { no: 121, char: "来", pinyin: "lái", meaning: "come" },
  { no: 122, char: "回", pinyin: "huí", meaning: "return" },
  { no: 123, char: "去", pinyin: "qù", meaning: "go" },
  { no: 124, char: "吃", pinyin: "chī", meaning: "eat" },
  { no: 125, char: "喝", pinyin: "hē", meaning: "drink" },
  { no: 126, char: "睡觉", pinyin: "shuìjiào", meaning: "sleep" },
  { no: 127, char: "打电话", pinyin: "dǎdiànhuà", meaning: "make phone call" },
  { no: 128, char: "做", pinyin: "zuò", meaning: "do" },
  { no: 129, char: "买", pinyin: "mǎi", meaning: "buy" },
  { no: 130, char: "开", pinyin: "kāi", meaning: "open" },
  { no: 131, char: "坐", pinyin: "zuò", meaning: "sit" },
  { no: 132, char: "住", pinyin: "zhù", meaning: "live" },
  { no: 133, char: "学习", pinyin: "xuéxí", meaning: "study" },
  { no: 134, char: "工作", pinyin: "gōngzuò", meaning: "work" },
  { no: 135, char: "下雨", pinyin: "xiàyǔ", meaning: "rain" },
  { no: 136, char: "爱", pinyin: "ài", meaning: "love" },
  { no: 137, char: "喜欢", pinyin: "xǐhuān", meaning: "love, like" },
  { no: 138, char: "想", pinyin: "xiǎng", meaning: "want" },
  { no: 139, char: "认识", pinyin: "rènshi", meaning: "know" },
  { no: 140, char: "会", pinyin: "huì", meaning: "can" },
  { no: 141, char: "能", pinyin: "néng", meaning: "can, be able to" },
  { no: 142, char: "好", pinyin: "hǎo", meaning: "good" },
  { no: 143, char: "大", pinyin: "dà", meaning: "big" },
  { no: 144, char: "小", pinyin: "xiǎo", meaning: "small" },
  { no: 145, char: "多", pinyin: "duō", meaning: "many, much" },
  { no: 146, char: "少", pinyin: "shǎo", meaning: "few, little" },
  { no: 147, char: "冷", pinyin: "lěng", meaning: "cold" },
  { no: 148, char: "热", pinyin: "rè", meaning: "hot" },
  { no: 149, char: "高兴", pinyin: "gāoxìng", meaning: "happy" },
  { no: 150, char: "漂亮", pinyin: "piàoliang", meaning: "beautiful" }
];

const MANDARIN_BEAN_HSK2 = [
  { no: 1, char: "您", pinyin: "nín", meaning: "you" },
  { no: 2, char: "它", pinyin: "tā", meaning: "it" },
  { no: 3, char: "大家", pinyin: "dàjiā", meaning: "everyone" },
  { no: 4, char: "每", pinyin: "měi", meaning: "every, each" },
  { no: 5, char: "为什么", pinyin: "wèishénme", meaning: "why" },
  { no: 6, char: "零", pinyin: "líng", meaning: "zero" },
  { no: 7, char: "两", pinyin: "liǎng", meaning: "two" },
  { no: 8, char: "百", pinyin: "bǎi", meaning: "hundred" },
  { no: 9, char: "千", pinyin: "qiān", meaning: "thousand" },
  { no: 10, char: "第一", pinyin: "dìyī", meaning: "first" },
  { no: 11, char: "次", pinyin: "cì", meaning: "times" },
  { no: 12, char: "件", pinyin: "jiàn", meaning: "piece" },
  { no: 13, char: "别", pinyin: "bié", meaning: "do not" },
  { no: 14, char: "非常", pinyin: "fēicháng", meaning: "very" },
  { no: 15, char: "也", pinyin: "yě", meaning: "also" },
  { no: 16, char: "还", pinyin: "hái", meaning: "still" },
  { no: 17, char: "最", pinyin: "zuì", meaning: "the most" },
  { no: 18, char: "真", pinyin: "zhēn", meaning: "really" },
  { no: 19, char: "正在", pinyin: "zhèngzài", meaning: "be being" },
  { no: 20, char: "已经", pinyin: "yǐjīng", meaning: "already" },
  { no: 21, char: "一起", pinyin: "yìqǐ", meaning: "together" },
  { no: 22, char: "再", pinyin: "zài", meaning: "again" },
  // CORRECTION 2: 就 (HSK2 #23) pinyin is "jiù", not "jiǜ"
  { no: 23, char: "就", pinyin: "jiù", meaning: "at once" },
  { no: 24, char: "因为……所以……", pinyin: "yīnwèi...suǒyǐ…", meaning: "because…so…" },
  { no: 25, char: "虽然……但是……", pinyin: "suīrán…dànshì…", meaning: "although… but…" },
  { no: 26, char: "从", pinyin: "cóng", meaning: "from" },
  { no: 27, char: "比", pinyin: "bǐ", meaning: "comparing to" },
  { no: 28, char: "往", pinyin: "wǎng", meaning: "toward, to" },
  { no: 29, char: "离", pinyin: "lí", meaning: "indicate the distance between two objects" },
  { no: 30, char: "得", pinyin: "de", meaning: "" },
  { no: 31, char: "着", pinyin: "zhe", meaning: "" },
  { no: 32, char: "过", pinyin: "guò", meaning: "" },
  { no: 33, char: "吧", pinyin: "ba", meaning: "" },
  { no: 34, char: "机场", pinyin: "jīchǎng", meaning: "airport" },
  { no: 35, char: "教室", pinyin: "jiàoshì", meaning: "classroom" },
  { no: 36, char: "房间", pinyin: "fángjiān", meaning: "room" },
  { no: 37, char: "路", pinyin: "lù", meaning: "road" },
  { no: 38, char: "左边", pinyin: "zuǒbiān", meaning: "left" },
  { no: 39, char: "右边", pinyin: "yòubiān", meaning: "right" },
  { no: 40, char: "外", pinyin: "wài", meaning: "outside" },
  { no: 41, char: "旁边", pinyin: "pángbiān", meaning: "side" },
  { no: 42, char: "一下", pinyin: "yīxià", meaning: "in a short while" },
  { no: 43, char: "早上", pinyin: "zǎoshàng", meaning: "morning" },
  { no: 44, char: "晚上", pinyin: "wǎnshàng", meaning: "night" },
  { no: 45, char: "小时", pinyin: "xiǎoshí", meaning: "hour" },
  { no: 46, char: "时间", pinyin: "shíjiān", meaning: "time" },
  { no: 47, char: "去年", pinyin: "qùnián", meaning: "last year" },
  { no: 48, char: "日", pinyin: "rì", meaning: "date" },
  { no: 49, char: "生日", pinyin: "shēngrì", meaning: "birthday" },
  { no: 50, char: "哥哥", pinyin: "gēge", meaning: "older brother" },
  { no: 51, char: "姐姐", pinyin: "jiějie", meaning: "older sister" },
  { no: 52, char: "弟弟", pinyin: "dìdi", meaning: "younger brother" },
  { no: 53, char: "妹妹", pinyin: "mèimei", meaning: "younger sister" },
  { no: 54, char: "丈夫", pinyin: "zhàngfu", meaning: "husband" },
  { no: 55, char: "妻子", pinyin: "qīzi", meaning: "wife" },
  { no: 56, char: "孩子", pinyin: "háizi", meaning: "child" },
  { no: 57, char: "男人", pinyin: "nánrén", meaning: "man" },
  { no: 58, char: "女人", pinyin: "nǚrén", meaning: "woman" },
  { no: 59, char: "服务员", pinyin: "fúwùyuán", meaning: "waiter" },
  { no: 60, char: "鱼", pinyin: "yú", meaning: "fish" },
  { no: 61, char: "羊肉", pinyin: "yángròu", meaning: "mutton" },
  { no: 62, char: "牛奶", pinyin: "niúnǎi", meaning: "milk" },
  { no: 63, char: "鸡蛋", pinyin: "jīdàn", meaning: "egg" },
  { no: 64, char: "西瓜", pinyin: "xīguā", meaning: "watermelon" },
  { no: 65, char: "咖啡", pinyin: "kāfēi", meaning: "coffee" },
  { no: 66, char: "雪", pinyin: "xuě", meaning: "snow" },
  { no: 67, char: "药", pinyin: "yào", meaning: "medicine" },
  { no: 68, char: "手机", pinyin: "shǒujī", meaning: "cellphone" },
  { no: 69, char: "手表", pinyin: "shǒubiǎo", meaning: "watch" },
  { no: 70, char: "眼睛", pinyin: "yǎnjīng", meaning: "eye" },
  { no: 71, char: "身体", pinyin: "shēntǐ", meaning: "body" },
  { no: 72, char: "公共汽车", pinyin: "gōnggòngqìchē", meaning: "bus" },
  { no: 73, char: "报纸", pinyin: "bàozhǐ", meaning: "newspaper" },
  { no: 74, char: "门", pinyin: "mén", meaning: "door" },
  { no: 75, char: "题", pinyin: "tí", meaning: "topic, item" },
  { no: 76, char: "课", pinyin: "kè", meaning: "lesson" },
  { no: 77, char: "姓", pinyin: "xìng", meaning: "surname" },
  { no: 78, char: "问题", pinyin: "wèntí", meaning: "question" },
  { no: 79, char: "事情", pinyin: "shìqing", meaning: "matter" },
  { no: 80, char: "考试", pinyin: "kǎoshì", meaning: "exam" },
  { no: 81, char: "票", pinyin: "piào", meaning: "ticket" },
  { no: 82, char: "意思", pinyin: "yìsi", meaning: "meaning" },
  { no: 83, char: "颜色", pinyin: "yánsè", meaning: "color" },
  { no: 84, char: "铅笔", pinyin: "qiánbǐ", meaning: "pencil" },
  { no: 85, char: "面条", pinyin: "miàntiáo", meaning: "noodle" },
  { no: 86, char: "火车站", pinyin: "huǒchēzhàn", meaning: "train station" },
  { no: 87, char: "公司", pinyin: "gōngsī", meaning: "company" },
  // CORRECTION 3: 宾馆 (HSK2 #88) pinyin is "bīnguǎn", not "bīngguǎn"
  { no: 88, char: "宾馆", pinyin: "bīnguǎn", meaning: "hotel" },
  { no: 89, char: "说话", pinyin: "shuōhuà", meaning: "talk" },
  { no: 90, char: "卖", pinyin: "mài", meaning: "sell" },
  { no: 91, char: "问", pinyin: "wèn", meaning: "ask" },
  { no: 92, char: "走", pinyin: "zǒu", meaning: "walk" },
  { no: 93, char: "进", pinyin: "jìn", meaning: "enter" },
  { no: 94, char: "出", pinyin: "chū", meaning: "come" },
  { no: 95, char: "跑步", pinyin: "pǎobù", meaning: "run" },
  { no: 96, char: "到", pinyin: "dào", meaning: "arrive" },
  { no: 97, char: "穿", pinyin: "chuān", meaning: "wear" },
  { no: 98, char: "洗", pinyin: "xǐ", meaning: "wash" },
  { no: 99, char: "给", pinyin: "gěi", meaning: "give" },
  { no: 100, char: "找", pinyin: "zhǎo", meaning: "find" },
  { no: 101, char: "懂", pinyin: "dǒng", meaning: "understand" },
  { no: 102, char: "笑", pinyin: "xiào", meaning: "smile" },
  { no: 103, char: "告诉", pinyin: "gàosù", meaning: "tell" },
  { no: 104, char: "准备", pinyin: "zhǔnbèi", meaning: "prepare" },
  { no: 105, char: "开始", pinyin: "kāishǐ", meaning: "begin" },
  { no: 106, char: "介绍", pinyin: "jièshào", meaning: "introduce" },
  { no: 107, char: "帮助", pinyin: "bāngzhù", meaning: "help" },
  { no: 108, char: "玩", pinyin: "wán", meaning: "play" },
  { no: 109, char: "送", pinyin: "sòng", meaning: "present" },
  { no: 110, char: "等", pinyin: "děng", meaning: "wait" },
  { no: 111, char: "让", pinyin: "ràng", meaning: "let" },
  { no: 112, char: "起床", pinyin: "qǐchuáng", meaning: "get up" },
  { no: 113, char: "唱歌", pinyin: "chànggē", meaning: "sing" },
  { no: 114, char: "跳舞", pinyin: "tiàowǔ", meaning: "dance" },
  { no: 115, char: "旅游", pinyin: "lǚyóu", meaning: "travel" },
  { no: 116, char: "上班", pinyin: "shàngbān", meaning: "be on duty" },
  { no: 117, char: "生病", pinyin: "shēngbìng", meaning: "get ill, get sick" },
  { no: 118, char: "休息", pinyin: "xiūxi", meaning: "rest" },
  { no: 119, char: "运动", pinyin: "yùndòng", meaning: "exercise" },
  { no: 120, char: "游泳", pinyin: "yóuyǒng", meaning: "swim" },
  { no: 121, char: "踢足球", pinyin: "tīzúqiú", meaning: "play footbal" },
  { no: 122, char: "打篮球", pinyin: "dǎlánqiú", meaning: "play basketball" },
  { no: 123, char: "完", pinyin: "wán", meaning: "finish" },
  { no: 124, char: "觉得", pinyin: "juédé", meaning: "think" },
  { no: 125, char: "知道", pinyin: "zhīdao", meaning: "know" },
  { no: 126, char: "希望", pinyin: "xīwàng", meaning: "hope" },
  { no: 127, char: "可以", pinyin: "kěyǐ", meaning: "can" },
  { no: 128, char: "要", pinyin: "yào", meaning: "want" },
  { no: 129, char: "可能", pinyin: "kěnéng", meaning: "may" },
  { no: 130, char: "高", pinyin: "gāo", meaning: "tall" },
  { no: 131, char: "红", pinyin: "hóng", meaning: "red" },
  { no: 132, char: "白", pinyin: "bái", meaning: "white" },
  { no: 133, char: "黑", pinyin: "hēi", meaning: "black" },
  { no: 134, char: "忙", pinyin: "máng", meaning: "busy" },
  { no: 135, char: "快", pinyin: "kuài", meaning: "fast" },
  { no: 136, char: "慢", pinyin: "màn", meaning: "slow" },
  { no: 137, char: "远", pinyin: "yuǎn", meaning: "far" },
  { no: 138, char: "近", pinyin: "jìn", meaning: "close" },
  { no: 139, char: "好吃", pinyin: "hǎochī", meaning: "delicious" },
  { no: 140, char: "累", pinyin: "lèi", meaning: "tired" },
  { no: 141, char: "长", pinyin: "cháng", meaning: "long" },
  { no: 142, char: "新", pinyin: "xīn", meaning: "new" },
  { no: 143, char: "贵", pinyin: "guì", meaning: "expensive" },
  { no: 144, char: "便宜", pinyin: "piányi", meaning: "cheap" },
  { no: 145, char: "晴", pinyin: "qíng", meaning: "fine" },
  { no: 146, char: "阴", pinyin: "yīn", meaning: "cloudy" },
  { no: 147, char: "错", pinyin: "cuò", meaning: "wrong" },
  { no: 148, char: "快乐", pinyin: "kuàilè", meaning: "happy" },
  { no: 149, char: "对", pinyin: "duì", meaning: "to" },
  { no: 150, char: "对", pinyin: "duì", meaning: "right" }
];

const MANDARIN_BEAN_HSK3 = [
  { no: 1, char: "阿姨", pinyin: "āyí", meaning: "aunt" },
  { no: 2, char: "啊", pinyin: "a", meaning: "ah" },
  { no: 3, char: "矮", pinyin: "ǎi", meaning: "short" },
  { no: 4, char: "爱好", pinyin: "àihào", meaning: "hobby" },
  { no: 5, char: "安静", pinyin: "ānjìng", meaning: "Be quiet" },
  { no: 6, char: "把", pinyin: "bǎ", meaning: "hold" },
  { no: 7, char: "班", pinyin: "bān", meaning: "class" },
  { no: 8, char: "搬", pinyin: "bān", meaning: "move" },
  { no: 9, char: "半", pinyin: "bàn", meaning: "half" },
  { no: 10, char: "办法", pinyin: "bànfǎ", meaning: "Way" },
  { no: 11, char: "办公室", pinyin: "bàngōngshì", meaning: "Office" },
  { no: 12, char: "帮忙", pinyin: "bāngmáng", meaning: "Help" },
  { no: 13, char: "包", pinyin: "bāo", meaning: "package" },
  { no: 14, char: "饱", pinyin: "bǎo", meaning: "full" },
  { no: 15, char: "北方", pinyin: "běifāng", meaning: "north" },
  { no: 16, char: "被", pinyin: "bèi", meaning: "cover" },
  { no: 17, char: "鼻子", pinyin: "bízi", meaning: "nose" },
  { no: 18, char: "比较", pinyin: "bǐjiào", meaning: "compare" },
  { no: 19, char: "比赛", pinyin: "bǐsài", meaning: "Match" },
  { no: 20, char: "笔记本", pinyin: "bǐjìběn", meaning: "notebook" },
  { no: 21, char: "必须", pinyin: "bìxū", meaning: "Must" },
  { no: 22, char: "变化", pinyin: "biànhuà", meaning: "change" },
  { no: 23, char: "别人", pinyin: "biéren", meaning: "Others" },
  { no: 24, char: "冰箱", pinyin: "bīngxiāng", meaning: "Refrigerator" },
  { no: 25, char: "菜单", pinyin: "càidān", meaning: "menu" },
  { no: 26, char: "参加", pinyin: "cānjiā", meaning: "participate in" },
  { no: 27, char: "草", pinyin: "cǎo", meaning: "grass" },
  { no: 28, char: "层", pinyin: "céng", meaning: "layer" },
  { no: 29, char: "差", pinyin: "chà", meaning: "bad" },
  { no: 30, char: "超市", pinyin: "chāoshì", meaning: "Supermarket" },
  { no: 31, char: "衬衫", pinyin: "chènshān", meaning: "shirt" },
  { no: 32, char: "成绩", pinyin: "chéngjì", meaning: "achievement" },
  { no: 33, char: "城市", pinyin: "chéngshì", meaning: "City" },
  { no: 34, char: "迟到", pinyin: "chídào", meaning: "Late" },
  { no: 35, char: "除了", pinyin: "chúle", meaning: "except, besides" },
  { no: 36, char: "船", pinyin: "chuán", meaning: "ship" },
  { no: 37, char: "春", pinyin: "chūn", meaning: "spring" },
  { no: 38, char: "词典", pinyin: "cídiǎn", meaning: "Dictionaries" },
  { no: 39, char: "聪明", pinyin: "cōngming", meaning: "clever" },
  { no: 40, char: "打扫", pinyin: "dǎsǎo", meaning: "Clean" },
  { no: 41, char: "打算", pinyin: "dǎsuàn", meaning: "Plan" },
  { no: 42, char: "带", pinyin: "dài", meaning: "belt" },
  { no: 43, char: "担心", pinyin: "dānxīn", meaning: "Worry" },
  { no: 44, char: "蛋糕", pinyin: "dàngāo", meaning: "Cake" },
  { no: 45, char: "当然", pinyin: "dāngrán", meaning: "Of course" },
  // CORRECTION 4: 地 (HSK3 #46) meaning is missing in source PDF — leave blank
  { no: 46, char: "地", pinyin: "de", meaning: "" },
  { no: 47, char: "灯", pinyin: "dēng", meaning: "lamp" },
  { no: 48, char: "地方", pinyin: "dìfang", meaning: "local" },
  { no: 49, char: "地铁", pinyin: "dìtiě", meaning: "metro" },
  { no: 50, char: "地图", pinyin: "dìtú", meaning: "Map" },
  { no: 51, char: "电梯", pinyin: "diàntī", meaning: "Elevator." },
  { no: 52, char: "电子邮件", pinyin: "diànzǐyóujiàn", meaning: "E-mail" },
  { no: 53, char: "东", pinyin: "dōng", meaning: "east" },
  { no: 54, char: "冬", pinyin: "dōng", meaning: "winter" },
  { no: 55, char: "动物", pinyin: "dòngwù", meaning: "Animal" },
  { no: 56, char: "短", pinyin: "duǎn", meaning: "short" },
  { no: 57, char: "段", pinyin: "duàn", meaning: "paragraph" },
  { no: 58, char: "锻炼", pinyin: "duànliàn", meaning: "Physical exercise" },
  { no: 59, char: "多么", pinyin: "duōme", meaning: "such" },
  { no: 60, char: "饿", pinyin: "è", meaning: "hungry" },
  { no: 61, char: "不但……而且……", pinyin: "búdàn...érqiě…", meaning: "not only…but also…" },
  { no: 62, char: "耳朵", pinyin: "ěrduo", meaning: "Ears" },
  { no: 63, char: "发", pinyin: "fā", meaning: "send out" },
  { no: 64, char: "发烧", pinyin: "fāshāo", meaning: "Have a fever" },
  { no: 65, char: "发现", pinyin: "fāxiàn", meaning: "find, discover" },
  { no: 66, char: "方便", pinyin: "fāngbiàn", meaning: "convenient" },
  { no: 67, char: "放", pinyin: "fàng", meaning: "discharge" },
  { no: 68, char: "放心", pinyin: "fàngxīn", meaning: "Don't worry" },
  { no: 69, char: "分", pinyin: "fēn", meaning: "minute" },
  { no: 70, char: "附近", pinyin: "fùjìn", meaning: "nearby" },
  { no: 71, char: "复习", pinyin: "fùxí", meaning: "Review" },
  { no: 72, char: "干净", pinyin: "gānjìng", meaning: "clean" },
  { no: 73, char: "感兴趣", pinyin: "gǎnxìngqù", meaning: "be intretested in" },
  { no: 74, char: "感冒", pinyin: "gǎnmào", meaning: "get a cold" },
  { no: 75, char: "刚才", pinyin: "gāngcái", meaning: "just" },
  { no: 76, char: "个子", pinyin: "gèzi", meaning: "height" },
  { no: 77, char: "跟", pinyin: "gēn", meaning: "with" },
  { no: 78, char: "根据", pinyin: "gēnjù", meaning: "according to" },
  { no: 79, char: "更", pinyin: "gèng", meaning: "more" },
  { no: 80, char: "公斤", pinyin: "gōngjīn", meaning: "Kg." },
  { no: 81, char: "公园", pinyin: "gōngyuán", meaning: "Park" },
  { no: 82, char: "故事", pinyin: "gùshi", meaning: "Story" },
  { no: 83, char: "刮风", pinyin: "guāfēng", meaning: "Windy" },
  { no: 84, char: "关", pinyin: "guān", meaning: "shut" },
  { no: 85, char: "关系", pinyin: "guānxì", meaning: "relationship" },
  { no: 86, char: "关心", pinyin: "guānxīn", meaning: "Care for" },
  { no: 87, char: "关于", pinyin: "guānyú", meaning: "about" },
  { no: 88, char: "国家", pinyin: "guójiā", meaning: "Country" },
  { no: 89, char: "过去", pinyin: "guòqù", meaning: "Past times" },
  { no: 90, char: "过（动词）", pinyin: "guò", meaning: "pass" },
  { no: 91, char: "还是", pinyin: "háishì", meaning: "still" },
  { no: 92, char: "害怕", pinyin: "hàipà", meaning: "Fear" },
  { no: 93, char: "黑板", pinyin: "hēibǎn", meaning: "blackboard" },
  { no: 94, char: "后来", pinyin: "hòulái", meaning: "later" },
  { no: 95, char: "护照", pinyin: "hùzhào", meaning: "passport" },
  { no: 96, char: "花（动词）", pinyin: "huā", meaning: "spend" },
  { no: 97, char: "花（名词）", pinyin: "huā", meaning: "flower" },
  { no: 98, char: "画", pinyin: "huà", meaning: "painting" },
  { no: 99, char: "坏", pinyin: "huài", meaning: "bad" },
  { no: 100, char: "欢迎", pinyin: "huānyíng", meaning: "Welcome" },
  { no: 101, char: "还（动词）", pinyin: "huán", meaning: "Return" },
  { no: 102, char: "环境", pinyin: "huánjìng", meaning: "Environment" },
  { no: 103, char: "换", pinyin: "huàn", meaning: "change" },
  { no: 104, char: "黄河", pinyin: "huánghé", meaning: "Yellow River" },
  { no: 105, char: "回答", pinyin: "huídá", meaning: "Answer" },
  { no: 106, char: "会议", pinyin: "huìyì", meaning: "Meeting" },
  { no: 107, char: "或者", pinyin: "huòzhě", meaning: "perhaps" },
  { no: 108, char: "几乎", pinyin: "jīhū", meaning: "almost" },
  { no: 109, char: "机会", pinyin: "jīhuì", meaning: "Opportunity" },
  { no: 110, char: "极", pinyin: "jí", meaning: "extremely" },
  { no: 111, char: "记得", pinyin: "jìde", meaning: "remember" },
  { no: 112, char: "季节", pinyin: "jìjié", meaning: "Season" },
  { no: 113, char: "检查", pinyin: "jiǎnchá", meaning: "inspect" },
  { no: 114, char: "简单", pinyin: "jiǎndān", meaning: "simple" },
  { no: 115, char: "健康", pinyin: "jiànkāng", meaning: "Healthy" },
  { no: 116, char: "见面", pinyin: "jiànmiàn", meaning: "meet" },
  { no: 117, char: "讲", pinyin: "jiǎng", meaning: "speak" },
  { no: 118, char: "教", pinyin: "jiāo", meaning: "teach" },
  { no: 119, char: "角", pinyin: "jiǎo", meaning: "horn" },
  { no: 120, char: "脚", pinyin: "jiǎo", meaning: "foot" },
  { no: 121, char: "接", pinyin: "jiē", meaning: "pick,get" },
  { no: 122, char: "街道", pinyin: "jiēdào", meaning: "Street" },
  { no: 123, char: "结婚", pinyin: "jiéhūn", meaning: "marry" },
  { no: 124, char: "结束", pinyin: "jiéshù", meaning: "End" },
  { no: 125, char: "节目", pinyin: "jiémù", meaning: "program" },
  { no: 126, char: "节日", pinyin: "jiérì", meaning: "festival" },
  { no: 127, char: "解决", pinyin: "jiějué", meaning: "Solve" },
  { no: 128, char: "借", pinyin: "jiè", meaning: "borrow" },
  { no: 129, char: "经常", pinyin: "jīngcháng", meaning: "Often" },
  { no: 130, char: "经过", pinyin: "jīngguò", meaning: "After, through" },
  { no: 131, char: "经理", pinyin: "jīnglǐ", meaning: "manager" },
  { no: 132, char: "久", pinyin: "jiǔ", meaning: "long" },
  { no: 133, char: "旧", pinyin: "jiù", meaning: "old,used" },
  { no: 134, char: "句子", pinyin: "jùzi", meaning: "sentence" },
  { no: 135, char: "决定", pinyin: "juédìng", meaning: "Decision" },
  { no: 136, char: "渴", pinyin: "kě", meaning: "thirsty" },
  { no: 137, char: "可爱", pinyin: "kě'ài", meaning: "Lovely" },
  { no: 138, char: "刻", pinyin: "kè", meaning: "moment" },
  { no: 139, char: "客人", pinyin: "kèrén", meaning: "Guest" },
  { no: 140, char: "空调", pinyin: "kōngtiáo", meaning: "Air conditioner" },
  { no: 141, char: "口", pinyin: "kǒu", meaning: "mouth" },
  { no: 142, char: "哭", pinyin: "kū", meaning: "cry" },
  { no: 143, char: "裤子", pinyin: "kùzi", meaning: "trousers" },
  { no: 144, char: "筷子", pinyin: "kuàizi", meaning: "chopsticks" },
  { no: 145, char: "蓝", pinyin: "lán", meaning: "blue" },
  { no: 146, char: "老", pinyin: "lǎo", meaning: "old" },
  { no: 147, char: "离开", pinyin: "líkāi", meaning: "leave" },
  { no: 148, char: "礼物", pinyin: "lǐwù", meaning: "gift" },
  { no: 149, char: "历史", pinyin: "lìshǐ", meaning: "History" },
  { no: 150, char: "脸", pinyin: "liǎn", meaning: "face" },
  { no: 151, char: "聊天", pinyin: "liáotiān", meaning: "chat" },
  { no: 152, char: "练习", pinyin: "liànxí", meaning: "Practice" },
  { no: 153, char: "辆", pinyin: "liàng", meaning: "Car" },
  { no: 154, char: "了解", pinyin: "liǎojiě", meaning: "understand" },
  { no: 155, char: "邻居", pinyin: "línjū", meaning: "neighbor" },
  { no: 156, char: "留学", pinyin: "liúxué", meaning: "Overseas Study" },
  { no: 157, char: "楼", pinyin: "lóu", meaning: "floor" },
  { no: 158, char: "绿", pinyin: "lǜ", meaning: "green" },
  { no: 159, char: "马", pinyin: "mǎ", meaning: "Horse" },
  { no: 160, char: "马上", pinyin: "mǎshàng", meaning: "Right off" },
  { no: 161, char: "满意", pinyin: "mǎnyì", meaning: "Satisfied" },
  { no: 162, char: "帽子", pinyin: "màozi", meaning: "Hat" },
  { no: 163, char: "米", pinyin: "mǐ", meaning: "rice" },
  { no: 164, char: "面包", pinyin: "miànbāo", meaning: "Bread" },
  { no: 165, char: "明白", pinyin: "míngbai", meaning: "clear" },
  { no: 166, char: "拿", pinyin: "ná", meaning: "take" },
  { no: 167, char: "奶奶", pinyin: "nǎinai", meaning: "grandma" },
  { no: 168, char: "南", pinyin: "nán", meaning: "south" },
  { no: 169, char: "难", pinyin: "nán", meaning: "difficult" },
  { no: 170, char: "难过", pinyin: "nánguò", meaning: "sad" },
  { no: 171, char: "年级", pinyin: "niánjí", meaning: "grade" },
  { no: 172, char: "年轻", pinyin: "niánqīng", meaning: "Young" },
  { no: 173, char: "鸟", pinyin: "niǎo", meaning: "bird" },
  { no: 174, char: "努力", pinyin: "nǔlì", meaning: "Strive" },
  { no: 175, char: "爬山", pinyin: "páshān", meaning: "Mountain climbing" },
  { no: 176, char: "盘子", pinyin: "pánzi", meaning: "plate" },
  { no: 177, char: "胖", pinyin: "pàng", meaning: "fat" },
  { no: 178, char: "啤酒", pinyin: "píjiǔ", meaning: "Beer" },
  { no: 179, char: "皮鞋", pinyin: "píxié", meaning: "leather shoes" },
  { no: 180, char: "瓶子", pinyin: "píngzi", meaning: "bottle" },
  { no: 181, char: "其实", pinyin: "qíshí", meaning: "actually" },
  { no: 182, char: "其他", pinyin: "qítā", meaning: "Other" },
  { no: 183, char: "骑", pinyin: "qí", meaning: "ride" },
  { no: 184, char: "奇怪", pinyin: "qíguài", meaning: "strange" },
  { no: 185, char: "起来", pinyin: "qǐlái", meaning: "get up" },
  { no: 186, char: "起飞", pinyin: "qǐfēi", meaning: "take off" },
  { no: 187, char: "清楚", pinyin: "qīngchu", meaning: "clear" },
  { no: 188, char: "请假", pinyin: "qǐngjià", meaning: "ask for leave" },
  { no: 189, char: "秋", pinyin: "qiū", meaning: "autumn" },
  { no: 190, char: "裙子", pinyin: "qúnzi", meaning: "skirt" },
  { no: 191, char: "然后", pinyin: "ránhòu", meaning: "Then" },
  { no: 192, char: "热情", pinyin: "rèqíng", meaning: "Enthusiasm" },
  { no: 193, char: "认为", pinyin: "rènwéi", meaning: "think" },
  { no: 194, char: "认真", pinyin: "rènzhēn", meaning: "earnest" },
  { no: 195, char: "容易", pinyin: "róngyì", meaning: "easily" },
  { no: 196, char: "如果", pinyin: "rúguǒ", meaning: "If" },
  { no: 197, char: "伞", pinyin: "sǎn", meaning: "umbrella" },
  { no: 198, char: "上网", pinyin: "shàngwǎng", meaning: "Surf the Internet" },
  { no: 199, char: "生气", pinyin: "shēngqì", meaning: "get angry" },
  { no: 200, char: "声音", pinyin: "shēngyīn", meaning: "voice" },
  { no: 201, char: "试", pinyin: "shì", meaning: "try" },
  { no: 202, char: "世界", pinyin: "shìjiè", meaning: "world" },
  { no: 203, char: "瘦", pinyin: "shòu", meaning: "thin" },
  { no: 204, char: "舒服", pinyin: "shūfu", meaning: "comfortable" },
  { no: 205, char: "叔叔", pinyin: "shūshu", meaning: "uncle" },
  { no: 206, char: "树", pinyin: "shù", meaning: "tree" },
  { no: 207, char: "数学", pinyin: "shùxué", meaning: "Mathematics" },
  { no: 208, char: "刷牙", pinyin: "shuāyá", meaning: "Brush one's teeth" },
  { no: 209, char: "双", pinyin: "shuāng", meaning: "double, pair" },
  { no: 210, char: "水平", pinyin: "shuǐpíng", meaning: "level" },
  { no: 211, char: "司机", pinyin: "sījī", meaning: "Driver" },
  { no: 212, char: "太阳", pinyin: "tàiyáng", meaning: "sun" },
  { no: 213, char: "特别", pinyin: "tèbié", meaning: "Especially" },
  { no: 214, char: "疼", pinyin: "téng", meaning: "hurt" },
  { no: 215, char: "提高", pinyin: "tígāo", meaning: "increase" },
  { no: 216, char: "体育", pinyin: "tǐyù", meaning: "Sports" },
  { no: 217, char: "甜", pinyin: "tián", meaning: "sweet" },
  { no: 218, char: "条", pinyin: "tiáo", meaning: "strip" },
  { no: 219, char: "同事", pinyin: "tóngshì", meaning: "Colleague" },
  { no: 220, char: "同意", pinyin: "tóngyì", meaning: "Agree" },
  { no: 221, char: "头发", pinyin: "tóufa", meaning: "Hair" },
  { no: 222, char: "突然", pinyin: "tūrán", meaning: "suddenly" },
  { no: 223, char: "图书馆", pinyin: "túshūguǎn", meaning: "Library" },
  { no: 224, char: "腿", pinyin: "tuǐ", meaning: "leg" },
  { no: 225, char: "完成", pinyin: "wánchéng", meaning: "complete" },
  { no: 226, char: "碗", pinyin: "wǎn", meaning: "bowl" },
  { no: 227, char: "万", pinyin: "wàn", meaning: "ten thousand" },
  { no: 228, char: "忘记", pinyin: "wàngjì", meaning: "forget" },
  { no: 229, char: "为", pinyin: "wèi", meaning: "for" },
  { no: 230, char: "为了", pinyin: "wèile", meaning: "in order to" },
  { no: 231, char: "位", pinyin: "wèi", meaning: "position" },
  { no: 232, char: "文化", pinyin: "wénhuà", meaning: "Culture" },
  { no: 233, char: "西", pinyin: "xī", meaning: "west" },
  { no: 234, char: "习惯", pinyin: "xíguàn", meaning: "Habit" },
  { no: 235, char: "洗手间", pinyin: "xǐshǒujiān", meaning: "Restroom" },
  { no: 236, char: "洗澡", pinyin: "xǐzǎo", meaning: "Take a shower" },
  { no: 237, char: "夏", pinyin: "xià", meaning: "summer" },
  { no: 238, char: "先", pinyin: "xiān", meaning: "first" },
  { no: 239, char: "香蕉", pinyin: "xiāngjiāo", meaning: "Banana" },
  { no: 240, char: "相信", pinyin: "xiāngxìn", meaning: "believe" },
  { no: 241, char: "向", pinyin: "xiàng", meaning: "towards" },
  { no: 242, char: "像", pinyin: "xiàng", meaning: "image" },
  { no: 243, char: "小心", pinyin: "xiǎoxīn", meaning: "watch out" },
  { no: 244, char: "校长", pinyin: "xiàozhǎng", meaning: "Principal" },
  { no: 245, char: "新闻", pinyin: "xīnwén", meaning: "news" },
  { no: 246, char: "新鲜", pinyin: "xīnxiān", meaning: "fresh" },
  { no: 247, char: "信用卡", pinyin: "xìnyòngkǎ", meaning: "Credit card" },
  { no: 248, char: "行李箱", pinyin: "xínglixiāng", meaning: "Trunk" },
  { no: 249, char: "熊猫", pinyin: "xióngmāo", meaning: "Panda" },
  { no: 250, char: "需要", pinyin: "xūyào", meaning: "Need" },
  { no: 251, char: "选择", pinyin: "xuǎnzé", meaning: "Choice" },
  { no: 252, char: "要求", pinyin: "yāoqiú", meaning: "Requirement" },
  { no: 253, char: "爷爷", pinyin: "yéye", meaning: "grandpa" },
  { no: 254, char: "一定", pinyin: "yídìng", meaning: "Certain" },
  { no: 255, char: "一共", pinyin: "yígòng", meaning: "Altogether" },
  { no: 256, char: "一会儿", pinyin: "yíhuìr", meaning: "a while" },
  { no: 257, char: "一样", pinyin: "yíyàng", meaning: "equally" },
  { no: 258, char: "以前", pinyin: "yǐqián", meaning: "before" },
  { no: 259, char: "一般", pinyin: "yìbān", meaning: "commonly" },
  { no: 260, char: "一边", pinyin: "yìbiān", meaning: "One side" },
  { no: 261, char: "一直", pinyin: "yìzhí", meaning: "always" },
  { no: 262, char: "音乐", pinyin: "yīnyuè", meaning: "Music" },
  { no: 263, char: "银行", pinyin: "yínháng", meaning: "Bank" },
  { no: 264, char: "饮料", pinyin: "yǐnliào", meaning: "Drinks" },
  { no: 265, char: "应该", pinyin: "yīnggāi", meaning: "Should" },
  { no: 266, char: "影响", pinyin: "yǐngxiǎng", meaning: "Influence" },
  { no: 267, char: "用", pinyin: "yòng", meaning: "use" },
  { no: 268, char: "游戏", pinyin: "yóuxì", meaning: "Game" },
  { no: 269, char: "有名", pinyin: "yǒumíng", meaning: "Famous" },
  { no: 270, char: "又", pinyin: "yòu", meaning: "again" },
  { no: 271, char: "遇到", pinyin: "yùdào", meaning: "encounter" },
  { no: 272, char: "元", pinyin: "yuán", meaning: "element; yuan" },
  { no: 273, char: "愿意", pinyin: "yuànyì", meaning: "Be willing" },
  { no: 274, char: "月亮", pinyin: "yuèliang", meaning: "Moon" },
  { no: 275, char: "越", pinyin: "yuè", meaning: "the more" },
  { no: 276, char: "站", pinyin: "zhàn", meaning: "station" },
  { no: 277, char: "张", pinyin: "zhāng", meaning: "Zhang (surname)" },
  { no: 278, char: "长（动词）", pinyin: "zhǎng", meaning: "grow" },
  { no: 279, char: "着急", pinyin: "zháojí", meaning: "Worry" },
  { no: 280, char: "照顾", pinyin: "zhàogù", meaning: "look after" },
  { no: 281, char: "照片", pinyin: "zhàopiàn", meaning: "Photo" },
  { no: 282, char: "照相机", pinyin: "zhàoxiàngjī", meaning: "Camera" },
  { no: 283, char: "只（量词）", pinyin: "zhī", meaning: "(measure word)" },
  { no: 284, char: "只（副词）", pinyin: "zhǐ", meaning: "only" },
  { no: 285, char: "只有……才……", pinyin: "zhǐyǒu…cái…", meaning: "only if" },
  { no: 286, char: "中文", pinyin: "zhōngwén", meaning: "Chinese" },
  { no: 287, char: "中间", pinyin: "zhōngjiān", meaning: "Middle" },
  { no: 288, char: "终于", pinyin: "zhōngyú", meaning: "finally" },
  { no: 289, char: "种", pinyin: "zhǒng", meaning: "species" },
  { no: 290, char: "重要", pinyin: "zhòngyào", meaning: "important" },
  { no: 291, char: "周末", pinyin: "zhōumò", meaning: "Weekend" },
  { no: 292, char: "主要", pinyin: "zhǔyào", meaning: "main" },
  { no: 293, char: "注意", pinyin: "zhùyì", meaning: "Be careful" },
  { no: 294, char: "自己", pinyin: "zìjǐ", meaning: "Own, self" },
  { no: 295, char: "自行车", pinyin: "zìxíngchē", meaning: "Bicycle" },
  { no: 296, char: "总是", pinyin: "zǒngshì", meaning: "always" },
  { no: 297, char: "嘴", pinyin: "zuǐ", meaning: "mouth" },
  { no: 298, char: "最后", pinyin: "zuìhòu", meaning: "Last" },
  { no: 299, char: "最近", pinyin: "zuìjìn", meaning: "lately" },
  { no: 300, char: "作业", pinyin: "zuòyè", meaning: "homework" }
];

// Helper to strip parenthetical qualifiers e.g. "这（这儿）" -> "这", "过（动词）" -> "过"
function cleanCharacterKey(charStr) {
  return charStr.replace(/（[^）]+）|\([^\)]+\)/g, '').trim();
}

// Normalize pinyin for comparison (convert diacritics to numeric tone, strip spaces/punctuation)
function normalizePinyin(str) {
  if (!str) return '';
  return str.toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/ü/g, 'u')
    .replace(/v/g, 'u')
    .replace(/[^a-z0-9]/g, '');
}

function runDiff() {
  const dataDir = path.join(__dirname, '../data');
  const hsk1Data = JSON.parse(fs.readFileSync(path.join(dataDir, 'hsk1.json'), 'utf8'));
  const hsk2Data = JSON.parse(fs.readFileSync(path.join(dataDir, 'hsk2.json'), 'utf8'));
  const hsk3Data = JSON.parse(fs.readFileSync(path.join(dataDir, 'hsk3.json'), 'utf8'));

  // Combine existing datasets into a single lookup map by character
  const existingMap = new Map();
  [...hsk1Data, ...hsk2Data, ...hsk3Data].forEach(entry => {
    existingMap.set(entry.character, entry);
  });

  const allMandarinBeanRows = [
    ...MANDARIN_BEAN_HSK1.map(item => ({ ...item, level: 'HSK1' })),
    ...MANDARIN_BEAN_HSK2.map(item => ({ ...item, level: 'HSK2' })),
    ...MANDARIN_BEAN_HSK3.map(item => ({ ...item, level: 'HSK3' }))
  ];

  const missingEntries = [];
  const mismatches = [];
  const nonWordEntries = [];

  allMandarinBeanRows.forEach(item => {
    const rawChar = item.char;

    // Report c: Non-word entries (grammar patterns e.g. 因为……所以……)
    if (rawChar.includes('…') || rawChar.includes('...') || rawChar.includes('..')) {
      nonWordEntries.push({
        level: item.level,
        no: item.no,
        character: rawChar,
        pinyin: item.pinyin,
        meaning: item.meaning
      });
      return;
    }

    const cleanChar = cleanCharacterKey(rawChar);
    const existingEntry = existingMap.get(cleanChar) || existingMap.get(rawChar);

    // Report a: Missing entries
    if (!existingEntry) {
      missingEntries.push({
        level: item.level,
        no: item.no,
        character: rawChar,
        cleanCharacter: cleanChar,
        pinyin: item.pinyin,
        meaning: item.meaning
      });
      return;
    }

    // Report b: Pinyin or Meaning mismatches
    const mbPinyinNorm = normalizePinyin(item.pinyin);
    const existingPinyins = Array.isArray(existingEntry.pinyin) ? existingEntry.pinyin : [existingEntry.displayPinyin || ''];
    const pinyinMatches = existingPinyins.some(p => normalizePinyin(p) === mbPinyinNorm);

    // Flag if pinyin doesn't match OR if meaning differs significantly OR if meaning is explicitly blank (e.g. 地)
    const isBlankMeaning = item.meaning === "";
    const existingMeaning = (existingEntry.meaning || "").toLowerCase();
    const mbMeaning = (item.meaning || "").toLowerCase();

    const meaningMatches = isBlankMeaning || existingMeaning.includes(mbMeaning) || mbMeaning.split(/[\/\,\s]+/).some(w => w.length > 2 && existingMeaning.includes(w));

    if (!pinyinMatches || !meaningMatches || isBlankMeaning) {
      mismatches.push({
        level: item.level,
        no: item.no,
        character: rawChar,
        cleanCharacter: cleanChar,
        mandarinBeanPinyin: item.pinyin,
        existingPinyin: existingEntry.displayPinyin || existingEntry.pinyin,
        mandarinBeanMeaning: item.meaning,
        existingMeaning: existingEntry.meaning,
        isBlankMeaning: isBlankMeaning
      });
    }
  });

  return { missingEntries, mismatches, nonWordEntries };
}

if (require.main === module) {
  const result = runDiff();
  console.log('\n=== DIFF RESULTS SUMMARY ===\n');
  console.log(`a. Missing Entries Count: ${result.missingEntries.length}`);
  console.log(`b. Pinyin/Meaning Mismatches Count: ${result.mismatches.length}`);
  console.log(`c. Non-Word Grammar Pattern Entries Count: ${result.nonWordEntries.length}\n`);

  console.log('--- a. Missing Entries ---');
  console.log(JSON.stringify(result.missingEntries, null, 2));

  console.log('\n--- b. Mismatches ---');
  console.log(JSON.stringify(result.mismatches, null, 2));

  console.log('\n--- c. Non-Word Grammar Patterns ---');
  console.log(JSON.stringify(result.nonWordEntries, null, 2));
}

module.exports = { runDiff, MANDARIN_BEAN_HSK1, MANDARIN_BEAN_HSK2, MANDARIN_BEAN_HSK3 };
